### ISSUE TITLE
[question] respect .babelrc files

### ISSUE THREAD

**Issue by RafalFilipek** [belgattitude/next-transpile-ts-workspace#6]
Hi!

Thank you for this example and your work!

Is there any way to have `.babelrc` files in packages to customize babel settings. Let's say that I have `ui` package where I'm using emotion11. To make it work I need `.babelrc` with

```
{
  "plugins": ["@emotion"]
}
```

Can I somehow tweak `config.module.rule` or `defaultLoaders.babel`?

Thanks,

Rafal

**Comment by belgattitude** [comment]
Hey @RafalFilipek, In a monorepo use `babel.config.js` rather than `.babelrc` and all will generally work.

By the way, I've moved the work into a new repository:  https://github.com/belgattitude/nextjs-monorepo-example

If you open the issue, I'll give you the complete file :) Cause this repo was just a test
